//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyCookbook.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENT
    {
        public int RECIPE_ID { get; set; }
        public int FOOD_ID { get; set; }
        public string AMOUNT { get; set; }
        public Nullable<int> MEASUREMENT_ID { get; set; }
    
        public virtual FOOD_ITEM FOOD_ITEM { get; set; }
        public virtual MEASUREMENT MEASUREMENT { get; set; }
        public virtual RECIPE RECIPE { get; set; }
    }
}
