//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyCookbook.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECIPE()
        {
            this.INGREDIENTs = new HashSet<INGREDIENT>();
        }
    
        public int RECIPE_ID { get; set; }
        public string NAME { get; set; }
        public string SERVING_SIZE { get; set; }
        public string SERVING_UNIT { get; set; }
        public int CATEGORY_ID { get; set; }
        public string INSTRUCTIONS { get; set; }
        public Nullable<int> AUTHOR_ID { get; set; }
    
        public virtual AUTHOR AUTHOR { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INGREDIENT> INGREDIENTs { get; set; }
    }
}
